### ISSUE TITLE
Requests are not being sent to Github

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-service-bot#10]
The two most recent requests weren't sent to Github: 

Date | ID | email | Application | What ...
-- | -- | -- | -- | --
10/29/2019 9:31 AM | DTS19-100295 | [Cari B] | [no application specified] | Something Else
10/28/2019 12:33 PM | DTS19-100290 | [Kati A] | [no application specified] | Something Else

**Comment by johnclary** [comment]
@amenity fixed and the issues have been created. had to update a rule in the knack app that sets the default application name when blank
