### ISSUE TITLE
Write Script to Extract Github + Zenhub Issues to CSV

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-service-bot#2]

**Comment by amenity** [comment]
@johnclary - cool if we close this and make a new issue when we want to work on it more?

**Comment by johnclary** [comment]
yep. closed. thanks :)

**Comment by johnclary** [comment]
the code lives in a dev branch: https://github.com/cityofaustin/atd-service-bot/tree/csv

**Comment by amenity** [comment]
Other related issues: 
https://github.com/cityofaustin/atd-service-bot/issues/3
https://github.com/cityofaustin/atd-knack-dts-portal/issues/4
https://github.com/cityofaustin/atd-knack-dts-portal/issues/3
https://github.com/cityofaustin/atd-knack-dts-portal/issues/2
