### ISSUE TITLE
Reverse text styles of form fields and data submitted in Github issue

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-service-bot#3]
@amenity commented on [Thu Oct 03 2019](https://github.com/cityofaustin/atd-knack-dts-portal/issues/5)

I think it would be more legible to see the text of the request in black rather than grey and formatted as a comment.  

**Currently**

<img width="705" alt="Screen Shot 2019-10-03 at 1 40 25 PM" src="https://user-images.githubusercontent.com/1463708/66155132-99f84680-e5e4-11e9-85bf-9d3130ae6b16.png">

**Better**
<img width="742" alt="Screen Shot 2019-10-03 at 1 42 54 PM" src="https://user-images.githubusercontent.com/1463708/66155134-99f84680-e5e4-11e9-9b67-5fe497e95e7e.png">

---

@amenity commented on [Thu Oct 03 2019](https://github.com/cityofaustin/atd-knack-dts-portal/issues/5#issuecomment-538077075)

Would also fix https://github.com/cityofaustin/atd-knack-dts-portal/issues/3, right @johnclary?

**Comment by johnclary** [comment]
agreed.
