### ISSUE TITLE
Bot is creating a million issues from one submission

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-service-bot#8]
One issue per minute, it appears. 😬

Chris McConnell only submitted the form once, but I have a steady stream of emails/issues coming in. 
![screencapture-github-cityofaustin-atd-data-tech-issues-2019-10-22-17_08_11](https://user-images.githubusercontent.com/1463708/67338818-88250780-f4ef-11e9-888e-548c9e662e52.png)

**Comment by johnclary** [comment]
I was unable to reproduce this issue, but I added some redundant rules in Knack to ensure that any SR that has a github issue will be flagged as `GITHUB_TRANSMISSION_STATUS=SENT`. Re-tested and all is working normally.
